### ISSUE TITLE
Feature(s) request: get OS info, Browser info and Screen resolution/focus from within jsPsych utilities

### ISSUE THREAD

**Issue by jcvanelst** [UiL-OTS-labs/jspsych-uil-utils#12]
In a series of what may become multiple feature requests. 

A utilities function or procedure to be used and re-used that could, for example be called easily within jsPsych code like such (on_start, on_load, on_finish methods, eg):

 ```javacript

        let start_screen = {
            type: 'html-button-response',
            on_start: // a call or something in the lines of: "uil.utils.getOperatingSystemInfo"/"getBrowserScreenResolution"
            stimulus: function(){
                return "<div class='instruction' >" +
                       "<p>" + GENERIC_CHECK + "</p></div>";
            },
            choices: [NEXT_BUTTON_TEXT],
            response_ends_trial: true
       //....//...};
```
The a above example is pseudocode and just a suggestion/question for how to use within certain trial , the goal is to be able to:

1. Query what kind of Operating System is being used (would typically not be called more often than once)
2. Query what browser (version) is used (would typically not be called more often than once)
3. Query __at multiple points in time during an experiment__ the '__current__' resolution and/or 'window focus'.

Let me know if this issue deserves more discussion, or more separate tickets for each request, i will edit according to feedback!

**Comment by jcvanelst** [comment]
thanks Ty. I hope to be able to use it soon! BTW @all, we dropped window focus, jsPsych has some tools for that, but well...maybe later.

**Comment by maartenuni** [comment]
@tymees @bbonf I think point 1 and 2 in the original question are covered in Ty's "Implemented browser info" that is merged ad april 29th 2021.
Do we want to work on the final point or shall we consider this issue as done?

**Comment by tymees** [comment]
Seeing as this issue has only now been revisited after more than 2 years, I think it's not really needed?

**Comment by maartenuni** [comment]
Closing this issue, if we desire the function mentioned in the OP, we can always create a new request.
