### ISSUE TITLE
Redirection to non-existant page.

### ISSUE THREAD

**Issue by maartenuni** [UiL-OTS-labs/jspsych-uil-utils#19]
It can be the case (e.g. no valid accesskey), that one is redirected to:
```javascript
const CRITICAL_ERROR_PAGE_LOCATION = 
        'https://web-experiments.lab.hum.uu.nl/index_files/error/';
```
However, that page doesn't exist. Hence, it creates more confusion than it solves...

**Comment by tymees** [comment]
Page does now exist
