### ISSUE TITLE
Redirect to "experiment closed" page when group assignment fails

### ISSUE THREAD

**Issue by bbonf** [UiL-OTS-labs/jspsych-uil-utils#21]

**Comment by bbonf** [comment]
It would fix the common cause (that is actually an expected use case), that's true.

But it could still be that the API call for starting a session fails and then you are left with a blank screen. Would you rather do something else in that case?

**Comment by tymees** [comment]
Hm yeah, we should do that. However, I do think the 'experiment closed' page is not the right approach. (As it could fail for other reasons). I'd say the (now still not existing) generic error page would be a better place to redirect.
