### ISSUE TITLE
loading of scripts fails when using file: protocol

### ISSUE THREAD

**Issue by maartenuni** [UiL-OTS-labs/jspsych-uil-utils#8]
Ik ben momenteel niet instaat om de uilutils te laden van een relatief path.

ls -l
```
maarten@maarten-workbook:~/github/jspsych-spr-mw$ ls -l
total 52
-rw-r--r-- 1 maarten maarten   519 nov 13 12:38 globals.js
-rw-r--r-- 1 maarten maarten  4938 nov 17 11:42 index.html
-rw-r--r-- 1 maarten maarten  2236 nov 13 12:43 instructions.js
lrwxrwxrwx 1 maarten maarten    56 nov 17 11:21 jsPsych-6.1.0 -> /home/maarten/github/jspsych-boilerplates/jsPsych-6.1.0/
-rw-r--r-- 1 maarten maarten 18092 nov 11 10:43 LICENSE
drwxr-xr-x 2 maarten maarten  4096 nov 11 13:44 plugins
-rw-r--r-- 1 maarten maarten    82 nov 11 10:43 README.md
-rw-r--r-- 1 maarten maarten  8071 nov 17 09:51 stimuli.js
lrwxrwxrwx 1 maarten maarten    39 nov 17 11:26 utils -> /home/maarten/github/jspsych-uil-utils/
```

The utilities zitten in een softlink naar de directory: `/home/maarten/github/jspsych-uil-utils/`

in jspsych-il-utils.js lijkt de variable SCRIPT_DIR te verwijzen naar: "file:///home/maarten/github/jspsych-spr-mw"
waar ik  "file:///home/maarten/github/jspsych-spr-mw/utils" zou verwachten.

In de header van index.html word het script als volgt geladen:
`<script src="./utils/jspsych-uil-utils.js"></script>`

Dit komt omdat ik momenteel niet thuis thuiswerk... <-- ik snap de verwarring :-).

**Comment by tymees** [comment]
Gebruik je de laatste versie van de utils?

Er was een bug die hier eng goed op lijkt laatst, die inmiddels gefixt is

**Comment by maartenuni** [comment]
Je hebt gelijk

**Comment by maartenuni** [comment]
This was fixed in: 0acef6b16e3cf25169c4d8236deaf39c6f5dcdfa
